Repository alliedmodders/sourcemod, pull requests merged in 2018-10, with the labels that each got.

#899 [NMRiH] Gamedata update
  gamedata/sdktools.games/game.nmrih.txt
Labels: Bug, Gamedata

#873 Restore SQL_CheckConfig Behavior
  core/logic/smn_database.cpp
Labels: Bug

#885 More TR natives
  extensions/sdktools/extension.cpp
  extensions/sdktools/extension.h
  extensions/sdktools/trnatives.cpp
  plugins/include/sdktools_trace.inc
Labels: Feature Request

#906 Handle NULLs in SDKCall string return (Fixes #874)
  extensions/sdktools/vcaller.cpp
Labels: Bug

#907 Use natural sorting for map lists (Fixes #892)
  core/logic/smn_maplists.cpp
Labels: Feature Request
