Repository alliedmodders/sourcemod, pull requests merged in 2019-04, with the labels that each got.

#979 Block loading of incompatible IBinTools interface
  public/extensions/IBinTools.h
Labels: Bug

#965 Add templated helper class to promote type-safety
  extensions/cstrike/natives.cpp
  extensions/cstrike/util_cstrike.cpp
  extensions/sdktools/inputnatives.cpp
  extensions/sdktools/outputnatives.cpp
  extensions/tf2/natives.cpp
  public/sm_argbuffer.h
Labels: Bug, Works For Me

#972 Add new custom kill identifier
  plugins/include/tf2_stocks.inc
Labels: Feature Request
