Repository alliedmodders/sourcemod, pull requests merged in 2019-05, with the labels that each got.

#999 Fix ArgBuffer String Serialization
  public/sm_argbuffer.h
Labels: Bug

#1024 NPOTB: Fix GCC 9 Builds
  AMBuildScript
Labels: NPOTB

#1022 Fix Miscellaneous Regressions and UBs
  core/logic/CellArray.h
  core/logic/ExtensionSys.cpp
  core/logic/ShareSys.cpp
  core/logic/stringutil.cpp
  core/smn_entities.cpp
  public/IExtensionSys.h
Labels: Bug

#1004 Created GlobalForward and Forward methodmaps
  core/logic/smn_functions.cpp
  plugins/adminmenu.sp
  plugins/include/functions.inc
  plugins/mapchooser.sp
Labels: Feature Request

#1012 Added cookie methodmap (clientprefs)
  core/smn_keyvalues.cpp
  extensions/clientprefs/natives.cpp
  plugins/include/clientprefs.inc
Labels: Feature Request
