Repository alliedmodders/sourcemod, pull requests merged in 2020-10, with the labels that each got.

#1358 NPOTB: Keep sourcemod loader bin in /bin/
  tools/buildbot/PackageScript
Labels: Bug, Works For Me

#1357 Kill CDataPack cache
  core/logic/CDataPack.cpp
  core/logic/CDataPack.h
  core/logic/smn_datapacks.cpp
Labels: Bug

#1367 Update credits
  core/PlayerManager.cpp
  core/logic/RootConsoleMenu.cpp
Labels: hacktoberfest-accepted

#1368 Fix spcomp64 filename for Windows
  tools/buildbot/PackageScript
Labels: Bug, hacktoberfest-accepted
