Repository alliedmodders/sourcemod, pull requests merged in 2020-05, with the labels that each got.

#1242 Add cmdreplysource check to notify player and misc formatting
  plugins/nextmap.sp
Labels: Feature Request

#1237 Update OnEntityDestroyed description
  plugins/include/sdkhooks.inc
Labels: Documentation

#1219 Add an Array variant to DataPack's Read/Write methods
  core/logic/CDataPack.cpp
  core/logic/CDataPack.h
  core/logic/smn_datapacks.cpp
  plugins/include/datapack.inc
Labels: Feature Request

#1256 Fix unnecessary ConCommand cache misses
  core/concmd_cleaner.cpp
  core/smn_console.cpp
Labels: Bug
