Repository alliedmodders/sourcemod, pull requests merged in 2020-07, with the labels that each got.

#977 sm_cookies now display a number before the cookie (without arguments) similar to sm_help
  plugins/clientprefs.sp
Labels: Feature Request

#1221 Change unnecessary int[]'s to any[]
  plugins/include/entity.inc
  plugins/include/files.inc
Labels: Feature Request

#1110 Track Handle Creation Time For Dump Outputs
  core/logic/HandleSys.cpp
  core/logic/HandleSys.h
  core/logic/smn_core.cpp
  extensions/sdktools/vhelpers.cpp
  public/sm_invalidparamhandler.h
  public/sm_platform.h
Labels: Feature Request, Works For Me

#1307 Add pcre lib for Windows x64 builds
  extensions/regex/AMBuilder
  extensions/regex/README.md
  extensions/regex/lib_win64/pcre.lib
Labels: Bug, Needs Testing

#1309 Update PCRE Dependency to 8.44 (bug 6650)
  extensions/regex/README.md
  extensions/regex/lib_darwin/libpcre.a
  extensions/regex/lib_darwin64/libpcre.a
  extensions/regex/lib_linux/libpcre.a
  extensions/regex/lib_linux64/libpcre.a
  extensions/regex/lib_win/pcre.lib
  extensions/regex/lib_win64/pcre.lib
  extensions/regex/pcre.h
Labels: Bug, Needs Testing

#969 Move appveyor in-tree and convert to MSVC2015.
  appveyor.yml
Labels: NPOTB

#852 Add Clone() implementation for StringMap
  core/logic/smn_adt_trie.cpp
  plugins/include/adt_trie.inc
  public/sm_trie_tpl.h
Labels: Feature Request

#1320 Fix lin64 pcre lib linking
  extensions/regex/README.md
  extensions/regex/lib_linux64/libpcre.a
Labels: Bug

#1321 Add x64 builds to travis-ci
  .travis.yml
Labels: NPOTB
